#!/usr/bin/env php
<?php

use Dotenv\Dotenv;
use Macedonia\Alex\Console;

require_once __DIR__ . "/vendor/autoload.php";

$dotEnv = Dotenv::createImmutable( __DIR__ );
$dotEnv->load();

const COMMANDS_PATH      = "/src/Console";
const COMMANDS_NAMESPACE = "\\Alexander\\Console";

$console = Console::getInstance();
$console->setRootNamespaceDir( __DIR__ . "/src" );
$console->addCommandsDir( __DIR__ . COMMANDS_PATH, COMMANDS_NAMESPACE );

try {
	$console->run();
} catch ( Exception $exception ) {
	echo $exception->getMessage();
	exit( 0 );
}
